spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmate
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: create-drop
  config:
    import: secrets.yaml